// <auto-generated />
using System;
using ERPProject.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPProject.Migrations.Migrations
{
    [DbContext(typeof(ERPDatabaseContext))]
    [Migration("20240427151359_Adding user bulk seeding")]
    partial class Addinguserbulkseeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPProject.Model.CustomerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerMobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedUserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "0,1");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("CustomerEmail")
                        .IsUnique();

                    b.HasIndex("CustomerMobile")
                        .IsUnique();

                    b.HasIndex("LastModifiedUserId");

                    b.ToTable("Customers", "Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-1, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27649@gmail.com",
                            CustomerMobile = "9800000001",
                            CustomerName = "Bijay Adhikari-1"
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-2, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27650@gmail.com",
                            CustomerMobile = "9800000002",
                            CustomerName = "Bijay Adhikari-2"
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-3, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27651@gmail.com",
                            CustomerMobile = "9800000003",
                            CustomerName = "Bijay Adhikari-3"
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-4, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27652@gmail.com",
                            CustomerMobile = "9800000004",
                            CustomerName = "Bijay Adhikari-4"
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-5, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27653@gmail.com",
                            CustomerMobile = "9800000005",
                            CustomerName = "Bijay Adhikari-5"
                        },
                        new
                        {
                            Id = 6,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-6, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27654@gmail.com",
                            CustomerMobile = "9800000006",
                            CustomerName = "Bijay Adhikari-6"
                        },
                        new
                        {
                            Id = 7,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-7, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27655@gmail.com",
                            CustomerMobile = "9800000007",
                            CustomerName = "Bijay Adhikari-7"
                        },
                        new
                        {
                            Id = 8,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-8, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27656@gmail.com",
                            CustomerMobile = "9800000008",
                            CustomerName = "Bijay Adhikari-8"
                        },
                        new
                        {
                            Id = 9,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-9, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27657@gmail.com",
                            CustomerMobile = "9800000009",
                            CustomerName = "Bijay Adhikari-9"
                        },
                        new
                        {
                            Id = 10,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-10, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27658@gmail.com",
                            CustomerMobile = "9800000010",
                            CustomerName = "Bijay Adhikari-10"
                        },
                        new
                        {
                            Id = 11,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-11, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27659@gmail.com",
                            CustomerMobile = "9800000011",
                            CustomerName = "Bijay Adhikari-11"
                        },
                        new
                        {
                            Id = 12,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-12, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27660@gmail.com",
                            CustomerMobile = "9800000012",
                            CustomerName = "Bijay Adhikari-12"
                        },
                        new
                        {
                            Id = 13,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-13, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27661@gmail.com",
                            CustomerMobile = "9800000013",
                            CustomerName = "Bijay Adhikari-13"
                        },
                        new
                        {
                            Id = 14,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-14, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27662@gmail.com",
                            CustomerMobile = "9800000014",
                            CustomerName = "Bijay Adhikari-14"
                        },
                        new
                        {
                            Id = 15,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-15, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27663@gmail.com",
                            CustomerMobile = "9800000015",
                            CustomerName = "Bijay Adhikari-15"
                        },
                        new
                        {
                            Id = 16,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-16, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27664@gmail.com",
                            CustomerMobile = "9800000016",
                            CustomerName = "Bijay Adhikari-16"
                        },
                        new
                        {
                            Id = 17,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-17, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27665@gmail.com",
                            CustomerMobile = "9800000017",
                            CustomerName = "Bijay Adhikari-17"
                        },
                        new
                        {
                            Id = 18,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-18, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27666@gmail.com",
                            CustomerMobile = "9800000018",
                            CustomerName = "Bijay Adhikari-18"
                        },
                        new
                        {
                            Id = 19,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-19, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27667@gmail.com",
                            CustomerMobile = "9800000019",
                            CustomerName = "Bijay Adhikari-19"
                        },
                        new
                        {
                            Id = 20,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-20, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27668@gmail.com",
                            CustomerMobile = "9800000020",
                            CustomerName = "Bijay Adhikari-20"
                        },
                        new
                        {
                            Id = 21,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-21, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27669@gmail.com",
                            CustomerMobile = "9800000021",
                            CustomerName = "Bijay Adhikari-21"
                        },
                        new
                        {
                            Id = 22,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-22, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27670@gmail.com",
                            CustomerMobile = "9800000022",
                            CustomerName = "Bijay Adhikari-22"
                        },
                        new
                        {
                            Id = 23,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-23, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27671@gmail.com",
                            CustomerMobile = "9800000023",
                            CustomerName = "Bijay Adhikari-23"
                        },
                        new
                        {
                            Id = 24,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-24, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27672@gmail.com",
                            CustomerMobile = "9800000024",
                            CustomerName = "Bijay Adhikari-24"
                        },
                        new
                        {
                            Id = 25,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-25, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27673@gmail.com",
                            CustomerMobile = "9800000025",
                            CustomerName = "Bijay Adhikari-25"
                        },
                        new
                        {
                            Id = 26,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-26, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27674@gmail.com",
                            CustomerMobile = "9800000026",
                            CustomerName = "Bijay Adhikari-26"
                        },
                        new
                        {
                            Id = 27,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-27, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27675@gmail.com",
                            CustomerMobile = "9800000027",
                            CustomerName = "Bijay Adhikari-27"
                        },
                        new
                        {
                            Id = 28,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-28, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27676@gmail.com",
                            CustomerMobile = "9800000028",
                            CustomerName = "Bijay Adhikari-28"
                        },
                        new
                        {
                            Id = 29,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-29, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27677@gmail.com",
                            CustomerMobile = "9800000029",
                            CustomerName = "Bijay Adhikari-29"
                        },
                        new
                        {
                            Id = 30,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-30, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27678@gmail.com",
                            CustomerMobile = "9800000030",
                            CustomerName = "Bijay Adhikari-30"
                        },
                        new
                        {
                            Id = 31,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-31, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27679@gmail.com",
                            CustomerMobile = "9800000031",
                            CustomerName = "Bijay Adhikari-31"
                        },
                        new
                        {
                            Id = 32,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-32, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27680@gmail.com",
                            CustomerMobile = "9800000032",
                            CustomerName = "Bijay Adhikari-32"
                        },
                        new
                        {
                            Id = 33,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-33, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27681@gmail.com",
                            CustomerMobile = "9800000033",
                            CustomerName = "Bijay Adhikari-33"
                        },
                        new
                        {
                            Id = 34,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-34, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27682@gmail.com",
                            CustomerMobile = "9800000034",
                            CustomerName = "Bijay Adhikari-34"
                        },
                        new
                        {
                            Id = 35,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-35, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27683@gmail.com",
                            CustomerMobile = "9800000035",
                            CustomerName = "Bijay Adhikari-35"
                        },
                        new
                        {
                            Id = 36,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-36, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27684@gmail.com",
                            CustomerMobile = "9800000036",
                            CustomerName = "Bijay Adhikari-36"
                        },
                        new
                        {
                            Id = 37,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-37, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27685@gmail.com",
                            CustomerMobile = "9800000037",
                            CustomerName = "Bijay Adhikari-37"
                        },
                        new
                        {
                            Id = 38,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-38, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27686@gmail.com",
                            CustomerMobile = "9800000038",
                            CustomerName = "Bijay Adhikari-38"
                        },
                        new
                        {
                            Id = 39,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-39, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27687@gmail.com",
                            CustomerMobile = "9800000039",
                            CustomerName = "Bijay Adhikari-39"
                        },
                        new
                        {
                            Id = 40,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-40, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27688@gmail.com",
                            CustomerMobile = "9800000040",
                            CustomerName = "Bijay Adhikari-40"
                        },
                        new
                        {
                            Id = 41,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-41, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27689@gmail.com",
                            CustomerMobile = "9800000041",
                            CustomerName = "Bijay Adhikari-41"
                        },
                        new
                        {
                            Id = 42,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-42, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27690@gmail.com",
                            CustomerMobile = "9800000042",
                            CustomerName = "Bijay Adhikari-42"
                        },
                        new
                        {
                            Id = 43,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-43, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27691@gmail.com",
                            CustomerMobile = "9800000043",
                            CustomerName = "Bijay Adhikari-43"
                        },
                        new
                        {
                            Id = 44,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-44, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27692@gmail.com",
                            CustomerMobile = "9800000044",
                            CustomerName = "Bijay Adhikari-44"
                        },
                        new
                        {
                            Id = 45,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-45, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27693@gmail.com",
                            CustomerMobile = "9800000045",
                            CustomerName = "Bijay Adhikari-45"
                        },
                        new
                        {
                            Id = 46,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-46, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27694@gmail.com",
                            CustomerMobile = "9800000046",
                            CustomerName = "Bijay Adhikari-46"
                        },
                        new
                        {
                            Id = 47,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-47, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27695@gmail.com",
                            CustomerMobile = "9800000047",
                            CustomerName = "Bijay Adhikari-47"
                        },
                        new
                        {
                            Id = 48,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-48, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27696@gmail.com",
                            CustomerMobile = "9800000048",
                            CustomerName = "Bijay Adhikari-48"
                        },
                        new
                        {
                            Id = 49,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-49, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27697@gmail.com",
                            CustomerMobile = "9800000049",
                            CustomerName = "Bijay Adhikari-49"
                        },
                        new
                        {
                            Id = 50,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-50, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27698@gmail.com",
                            CustomerMobile = "9800000050",
                            CustomerName = "Bijay Adhikari-50"
                        },
                        new
                        {
                            Id = 51,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-51, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27699@gmail.com",
                            CustomerMobile = "9800000051",
                            CustomerName = "Bijay Adhikari-51"
                        },
                        new
                        {
                            Id = 52,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-52, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27700@gmail.com",
                            CustomerMobile = "9800000052",
                            CustomerName = "Bijay Adhikari-52"
                        },
                        new
                        {
                            Id = 53,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-53, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27701@gmail.com",
                            CustomerMobile = "9800000053",
                            CustomerName = "Bijay Adhikari-53"
                        },
                        new
                        {
                            Id = 54,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-54, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27702@gmail.com",
                            CustomerMobile = "9800000054",
                            CustomerName = "Bijay Adhikari-54"
                        },
                        new
                        {
                            Id = 55,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-55, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27703@gmail.com",
                            CustomerMobile = "9800000055",
                            CustomerName = "Bijay Adhikari-55"
                        },
                        new
                        {
                            Id = 56,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-56, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27704@gmail.com",
                            CustomerMobile = "9800000056",
                            CustomerName = "Bijay Adhikari-56"
                        },
                        new
                        {
                            Id = 57,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-57, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27705@gmail.com",
                            CustomerMobile = "9800000057",
                            CustomerName = "Bijay Adhikari-57"
                        },
                        new
                        {
                            Id = 58,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-58, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27706@gmail.com",
                            CustomerMobile = "9800000058",
                            CustomerName = "Bijay Adhikari-58"
                        },
                        new
                        {
                            Id = 59,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-59, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27707@gmail.com",
                            CustomerMobile = "9800000059",
                            CustomerName = "Bijay Adhikari-59"
                        },
                        new
                        {
                            Id = 60,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-60, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27708@gmail.com",
                            CustomerMobile = "9800000060",
                            CustomerName = "Bijay Adhikari-60"
                        },
                        new
                        {
                            Id = 61,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-61, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27709@gmail.com",
                            CustomerMobile = "9800000061",
                            CustomerName = "Bijay Adhikari-61"
                        },
                        new
                        {
                            Id = 62,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-62, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27710@gmail.com",
                            CustomerMobile = "9800000062",
                            CustomerName = "Bijay Adhikari-62"
                        },
                        new
                        {
                            Id = 63,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-63, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27711@gmail.com",
                            CustomerMobile = "9800000063",
                            CustomerName = "Bijay Adhikari-63"
                        },
                        new
                        {
                            Id = 64,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-64, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27712@gmail.com",
                            CustomerMobile = "9800000064",
                            CustomerName = "Bijay Adhikari-64"
                        },
                        new
                        {
                            Id = 65,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-65, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27713@gmail.com",
                            CustomerMobile = "9800000065",
                            CustomerName = "Bijay Adhikari-65"
                        },
                        new
                        {
                            Id = 66,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-66, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27714@gmail.com",
                            CustomerMobile = "9800000066",
                            CustomerName = "Bijay Adhikari-66"
                        },
                        new
                        {
                            Id = 67,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-67, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27715@gmail.com",
                            CustomerMobile = "9800000067",
                            CustomerName = "Bijay Adhikari-67"
                        },
                        new
                        {
                            Id = 68,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-68, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27716@gmail.com",
                            CustomerMobile = "9800000068",
                            CustomerName = "Bijay Adhikari-68"
                        },
                        new
                        {
                            Id = 69,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-69, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27717@gmail.com",
                            CustomerMobile = "9800000069",
                            CustomerName = "Bijay Adhikari-69"
                        },
                        new
                        {
                            Id = 70,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-70, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27718@gmail.com",
                            CustomerMobile = "9800000070",
                            CustomerName = "Bijay Adhikari-70"
                        },
                        new
                        {
                            Id = 71,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-71, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27719@gmail.com",
                            CustomerMobile = "9800000071",
                            CustomerName = "Bijay Adhikari-71"
                        },
                        new
                        {
                            Id = 72,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-72, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27720@gmail.com",
                            CustomerMobile = "9800000072",
                            CustomerName = "Bijay Adhikari-72"
                        },
                        new
                        {
                            Id = 73,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-73, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27721@gmail.com",
                            CustomerMobile = "9800000073",
                            CustomerName = "Bijay Adhikari-73"
                        },
                        new
                        {
                            Id = 74,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-74, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27722@gmail.com",
                            CustomerMobile = "9800000074",
                            CustomerName = "Bijay Adhikari-74"
                        },
                        new
                        {
                            Id = 75,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-75, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27723@gmail.com",
                            CustomerMobile = "9800000075",
                            CustomerName = "Bijay Adhikari-75"
                        },
                        new
                        {
                            Id = 76,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-76, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27724@gmail.com",
                            CustomerMobile = "9800000076",
                            CustomerName = "Bijay Adhikari-76"
                        },
                        new
                        {
                            Id = 77,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-77, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27725@gmail.com",
                            CustomerMobile = "9800000077",
                            CustomerName = "Bijay Adhikari-77"
                        },
                        new
                        {
                            Id = 78,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-78, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27726@gmail.com",
                            CustomerMobile = "9800000078",
                            CustomerName = "Bijay Adhikari-78"
                        },
                        new
                        {
                            Id = 79,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-79, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27727@gmail.com",
                            CustomerMobile = "9800000079",
                            CustomerName = "Bijay Adhikari-79"
                        },
                        new
                        {
                            Id = 80,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-80, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27728@gmail.com",
                            CustomerMobile = "9800000080",
                            CustomerName = "Bijay Adhikari-80"
                        },
                        new
                        {
                            Id = 81,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-81, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27729@gmail.com",
                            CustomerMobile = "9800000081",
                            CustomerName = "Bijay Adhikari-81"
                        },
                        new
                        {
                            Id = 82,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-82, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27730@gmail.com",
                            CustomerMobile = "9800000082",
                            CustomerName = "Bijay Adhikari-82"
                        },
                        new
                        {
                            Id = 83,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-83, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27731@gmail.com",
                            CustomerMobile = "9800000083",
                            CustomerName = "Bijay Adhikari-83"
                        },
                        new
                        {
                            Id = 84,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-84, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27732@gmail.com",
                            CustomerMobile = "9800000084",
                            CustomerName = "Bijay Adhikari-84"
                        },
                        new
                        {
                            Id = 85,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-85, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27733@gmail.com",
                            CustomerMobile = "9800000085",
                            CustomerName = "Bijay Adhikari-85"
                        },
                        new
                        {
                            Id = 86,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-86, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27734@gmail.com",
                            CustomerMobile = "9800000086",
                            CustomerName = "Bijay Adhikari-86"
                        },
                        new
                        {
                            Id = 87,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-87, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27735@gmail.com",
                            CustomerMobile = "9800000087",
                            CustomerName = "Bijay Adhikari-87"
                        },
                        new
                        {
                            Id = 88,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-88, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27736@gmail.com",
                            CustomerMobile = "9800000088",
                            CustomerName = "Bijay Adhikari-88"
                        },
                        new
                        {
                            Id = 89,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-89, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27737@gmail.com",
                            CustomerMobile = "9800000089",
                            CustomerName = "Bijay Adhikari-89"
                        },
                        new
                        {
                            Id = 90,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-90, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27738@gmail.com",
                            CustomerMobile = "9800000090",
                            CustomerName = "Bijay Adhikari-90"
                        },
                        new
                        {
                            Id = 91,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-91, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27739@gmail.com",
                            CustomerMobile = "9800000091",
                            CustomerName = "Bijay Adhikari-91"
                        },
                        new
                        {
                            Id = 92,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-92, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27740@gmail.com",
                            CustomerMobile = "9800000092",
                            CustomerName = "Bijay Adhikari-92"
                        },
                        new
                        {
                            Id = 93,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-93, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27741@gmail.com",
                            CustomerMobile = "9800000093",
                            CustomerName = "Bijay Adhikari-93"
                        },
                        new
                        {
                            Id = 94,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-94, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27742@gmail.com",
                            CustomerMobile = "9800000094",
                            CustomerName = "Bijay Adhikari-94"
                        },
                        new
                        {
                            Id = 95,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-95, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27743@gmail.com",
                            CustomerMobile = "9800000095",
                            CustomerName = "Bijay Adhikari-95"
                        },
                        new
                        {
                            Id = 96,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-96, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27744@gmail.com",
                            CustomerMobile = "9800000096",
                            CustomerName = "Bijay Adhikari-96"
                        },
                        new
                        {
                            Id = 97,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-97, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27745@gmail.com",
                            CustomerMobile = "9800000097",
                            CustomerName = "Bijay Adhikari-97"
                        },
                        new
                        {
                            Id = 98,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-98, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27746@gmail.com",
                            CustomerMobile = "9800000098",
                            CustomerName = "Bijay Adhikari-98"
                        },
                        new
                        {
                            Id = 99,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-99, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27747@gmail.com",
                            CustomerMobile = "9800000099",
                            CustomerName = "Bijay Adhikari-99"
                        },
                        new
                        {
                            Id = 100,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-100, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27748@gmail.com",
                            CustomerMobile = "9800000100",
                            CustomerName = "Bijay Adhikari-100"
                        },
                        new
                        {
                            Id = 101,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            CustomerAddress = "Thaiba-101, Lalitpur",
                            CustomerEmail = "bijay.adhikari.27749@gmail.com",
                            CustomerMobile = "9800000101",
                            CustomerName = "Bijay Adhikari-101"
                        });
                });

            modelBuilder.Entity("ERPProject.Model.OrderDetailsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "0,1");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifiedUserId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", "Order");
                });

            modelBuilder.Entity("ERPProject.Model.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("OrderStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<float>("TotalAmount")
                        .HasColumnType("real");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "0,1");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LastModifiedUserId");

                    b.ToTable("Orders", "Order");
                });

            modelBuilder.Entity("ERPProject.Model.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("ProductPurchasePrice")
                        .HasColumnType("real");

                    b.Property<float>("ProductSellingPrice")
                        .HasColumnType("real");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "0,1");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifiedUserId");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("Products", "Store");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-1",
                            ProductPurchasePrice = 900f,
                            ProductSellingPrice = 1000f
                        },
                        new
                        {
                            Id = 2,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-2",
                            ProductPurchasePrice = 901f,
                            ProductSellingPrice = 1001f
                        },
                        new
                        {
                            Id = 3,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-3",
                            ProductPurchasePrice = 902f,
                            ProductSellingPrice = 1002f
                        },
                        new
                        {
                            Id = 4,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-4",
                            ProductPurchasePrice = 903f,
                            ProductSellingPrice = 1003f
                        },
                        new
                        {
                            Id = 5,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-5",
                            ProductPurchasePrice = 904f,
                            ProductSellingPrice = 1004f
                        },
                        new
                        {
                            Id = 6,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-6",
                            ProductPurchasePrice = 905f,
                            ProductSellingPrice = 1005f
                        },
                        new
                        {
                            Id = 7,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-7",
                            ProductPurchasePrice = 906f,
                            ProductSellingPrice = 1006f
                        },
                        new
                        {
                            Id = 8,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-8",
                            ProductPurchasePrice = 907f,
                            ProductSellingPrice = 1007f
                        },
                        new
                        {
                            Id = 9,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-9",
                            ProductPurchasePrice = 908f,
                            ProductSellingPrice = 1008f
                        },
                        new
                        {
                            Id = 10,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-10",
                            ProductPurchasePrice = 909f,
                            ProductSellingPrice = 1009f
                        },
                        new
                        {
                            Id = 11,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-11",
                            ProductPurchasePrice = 910f,
                            ProductSellingPrice = 1010f
                        },
                        new
                        {
                            Id = 12,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-12",
                            ProductPurchasePrice = 911f,
                            ProductSellingPrice = 1011f
                        },
                        new
                        {
                            Id = 13,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-13",
                            ProductPurchasePrice = 912f,
                            ProductSellingPrice = 1012f
                        },
                        new
                        {
                            Id = 14,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-14",
                            ProductPurchasePrice = 913f,
                            ProductSellingPrice = 1013f
                        },
                        new
                        {
                            Id = 15,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-15",
                            ProductPurchasePrice = 914f,
                            ProductSellingPrice = 1014f
                        },
                        new
                        {
                            Id = 16,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-16",
                            ProductPurchasePrice = 915f,
                            ProductSellingPrice = 1015f
                        },
                        new
                        {
                            Id = 17,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-17",
                            ProductPurchasePrice = 916f,
                            ProductSellingPrice = 1016f
                        },
                        new
                        {
                            Id = 18,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-18",
                            ProductPurchasePrice = 917f,
                            ProductSellingPrice = 1017f
                        },
                        new
                        {
                            Id = 19,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-19",
                            ProductPurchasePrice = 918f,
                            ProductSellingPrice = 1018f
                        },
                        new
                        {
                            Id = 20,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-20",
                            ProductPurchasePrice = 919f,
                            ProductSellingPrice = 1019f
                        },
                        new
                        {
                            Id = 21,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-21",
                            ProductPurchasePrice = 920f,
                            ProductSellingPrice = 1020f
                        },
                        new
                        {
                            Id = 22,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-22",
                            ProductPurchasePrice = 921f,
                            ProductSellingPrice = 1021f
                        },
                        new
                        {
                            Id = 23,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-23",
                            ProductPurchasePrice = 922f,
                            ProductSellingPrice = 1022f
                        },
                        new
                        {
                            Id = 24,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-24",
                            ProductPurchasePrice = 923f,
                            ProductSellingPrice = 1023f
                        },
                        new
                        {
                            Id = 25,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-25",
                            ProductPurchasePrice = 924f,
                            ProductSellingPrice = 1024f
                        },
                        new
                        {
                            Id = 26,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-26",
                            ProductPurchasePrice = 925f,
                            ProductSellingPrice = 1025f
                        },
                        new
                        {
                            Id = 27,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-27",
                            ProductPurchasePrice = 926f,
                            ProductSellingPrice = 1026f
                        },
                        new
                        {
                            Id = 28,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-28",
                            ProductPurchasePrice = 927f,
                            ProductSellingPrice = 1027f
                        },
                        new
                        {
                            Id = 29,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-29",
                            ProductPurchasePrice = 928f,
                            ProductSellingPrice = 1028f
                        },
                        new
                        {
                            Id = 30,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-30",
                            ProductPurchasePrice = 929f,
                            ProductSellingPrice = 1029f
                        },
                        new
                        {
                            Id = 31,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-31",
                            ProductPurchasePrice = 930f,
                            ProductSellingPrice = 1030f
                        },
                        new
                        {
                            Id = 32,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-32",
                            ProductPurchasePrice = 931f,
                            ProductSellingPrice = 1031f
                        },
                        new
                        {
                            Id = 33,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-33",
                            ProductPurchasePrice = 932f,
                            ProductSellingPrice = 1032f
                        },
                        new
                        {
                            Id = 34,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-34",
                            ProductPurchasePrice = 933f,
                            ProductSellingPrice = 1033f
                        },
                        new
                        {
                            Id = 35,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-35",
                            ProductPurchasePrice = 934f,
                            ProductSellingPrice = 1034f
                        },
                        new
                        {
                            Id = 36,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-36",
                            ProductPurchasePrice = 935f,
                            ProductSellingPrice = 1035f
                        },
                        new
                        {
                            Id = 37,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-37",
                            ProductPurchasePrice = 936f,
                            ProductSellingPrice = 1036f
                        },
                        new
                        {
                            Id = 38,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-38",
                            ProductPurchasePrice = 937f,
                            ProductSellingPrice = 1037f
                        },
                        new
                        {
                            Id = 39,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-39",
                            ProductPurchasePrice = 938f,
                            ProductSellingPrice = 1038f
                        },
                        new
                        {
                            Id = 40,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-40",
                            ProductPurchasePrice = 939f,
                            ProductSellingPrice = 1039f
                        },
                        new
                        {
                            Id = 41,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-41",
                            ProductPurchasePrice = 940f,
                            ProductSellingPrice = 1040f
                        },
                        new
                        {
                            Id = 42,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-42",
                            ProductPurchasePrice = 941f,
                            ProductSellingPrice = 1041f
                        },
                        new
                        {
                            Id = 43,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-43",
                            ProductPurchasePrice = 942f,
                            ProductSellingPrice = 1042f
                        },
                        new
                        {
                            Id = 44,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-44",
                            ProductPurchasePrice = 943f,
                            ProductSellingPrice = 1043f
                        },
                        new
                        {
                            Id = 45,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-45",
                            ProductPurchasePrice = 944f,
                            ProductSellingPrice = 1044f
                        },
                        new
                        {
                            Id = 46,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-46",
                            ProductPurchasePrice = 945f,
                            ProductSellingPrice = 1045f
                        },
                        new
                        {
                            Id = 47,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-47",
                            ProductPurchasePrice = 946f,
                            ProductSellingPrice = 1046f
                        },
                        new
                        {
                            Id = 48,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-48",
                            ProductPurchasePrice = 947f,
                            ProductSellingPrice = 1047f
                        },
                        new
                        {
                            Id = 49,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-49",
                            ProductPurchasePrice = 948f,
                            ProductSellingPrice = 1048f
                        },
                        new
                        {
                            Id = 50,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-50",
                            ProductPurchasePrice = 949f,
                            ProductSellingPrice = 1049f
                        },
                        new
                        {
                            Id = 51,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            CreatorUserId = 1,
                            ProductName = "Mango-51",
                            ProductPurchasePrice = 950f,
                            ProductSellingPrice = 1050f
                        });
                });

            modelBuilder.Entity("ERPProject.Model.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("LastModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastModifiedUserId")
                        .HasColumnType("int");

                    b.Property<string>("UserAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserMobile")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasAnnotation("SqlServer:Identity", "0,1");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("LastModifiedUserId");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.HasIndex("UserMobile")
                        .IsUnique();

                    b.ToTable("Users", "Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationTime = new DateTime(2024, 4, 27, 11, 47, 16, 85, DateTimeKind.Unspecified).AddTicks(3682),
                            FullName = "Bijay Adhikari",
                            UserAddress = "Thaiba, Lalitpur",
                            UserEmail = "bijay.adhikari.27648@gmail.com",
                            UserMobile = "9800000000"
                        });
                });

            modelBuilder.Entity("ERPProject.Model.CustomerModel", b =>
                {
                    b.HasOne("ERPProject.Model.UserModel", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPProject.Model.UserModel", "LastModifiedUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifiedUser");
                });

            modelBuilder.Entity("ERPProject.Model.OrderDetailsModel", b =>
                {
                    b.HasOne("ERPProject.Model.UserModel", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPProject.Model.UserModel", "LastModifiedUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPProject.Model.OrderModel", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPProject.Model.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifiedUser");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ERPProject.Model.OrderModel", b =>
                {
                    b.HasOne("ERPProject.Model.UserModel", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPProject.Model.CustomerModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPProject.Model.UserModel", "LastModifiedUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatorUser");

                    b.Navigation("Customer");

                    b.Navigation("LastModifiedUser");
                });

            modelBuilder.Entity("ERPProject.Model.ProductModel", b =>
                {
                    b.HasOne("ERPProject.Model.UserModel", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ERPProject.Model.UserModel", "LastModifiedUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifiedUser");
                });

            modelBuilder.Entity("ERPProject.Model.UserModel", b =>
                {
                    b.HasOne("ERPProject.Model.UserModel", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ERPProject.Model.UserModel", "LastModifiedUser")
                        .WithMany()
                        .HasForeignKey("LastModifiedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatorUser");

                    b.Navigation("LastModifiedUser");
                });
#pragma warning restore 612, 618
        }
    }
}
